### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by webber0971**
老師您好，我是李緯宸。 
老師抱歉，之前電腦送修，前兩周作業比較晚交不好意思。 
http://13.114.149.85:8888/ 
http://13.114.149.85:8888/attraction/2

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Layout for middle devices is not acceptable.
2. Layout of category block is obviously not align with design.
3. Border of search icon.

**Comment by webber0971** [comment]
I have fixed the above three errors .
Thanks teacher.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by cwpeng** [comment]
`images` field of attraction APIs should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`

**Review by cwpeng — CHANGES_REQUESTED** [review]
`images` field of attraction APIs should be a string array where every image URL of attraction should be a element in this array. For example: `["Image URL 1", "Image URL 2", ...]`

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
