### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by webber0971**
1.add login and register account interface
2.add api for login
3.use jwt to encrypt information as token and set token in cookie
4.use token in cookie to identify client is logged in or not

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Paste your live URLs for testing.

**Comment by webber0971** [comment]
我是李緯宸
http://13.114.149.85:8888/
http://13.114.149.85:8888/attraction/1

老師辛苦了!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Border style of input elements is not align with design.
2. Password input should use input element with type password.

**Comment by webber0971** [comment]
I've already corrected it.
我是李緯宸
http://13.114.149.85:8888/
http://13.114.149.85:8888/attraction/1

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
