### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by webber0971**
complete week5
changed bookingPage to book multiple trips at once
thanks

http://13.114.149.85:8888/
http://13.114.149.85:8888/attraction/3

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout issues, keep attention on details:
1. Add padding to your text or date input elements.
2. 聯絡姓名 repeating 3 times in your booking page.
3. There are separating lines in attraction page.

**Comment by webber0971** [comment]
I have corrected it ~

**Comment by webber0971** [comment]
我是李緯宸
http://13.114.149.85:8888/
http://13.114.149.85:8888/attraction/3

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Add padding to your text or date input elements.
2. We should show sign in/up dialog if we click on 開始預約行程 without signing in.

**Comment by webber0971** [comment]
Added padding in input elements at booking page~

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Add padding to your date input elements.
2. We should show sign in/up dialog if we click on 開始預約行程 without signing in.

Try to solve all issues at once. If you cannot get my point, contact me to clarify anytime in discord.

**Comment by webber0971** [comment]
1. added padding in date element at attractionPage
2. already checked,it is working

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
